### ISSUE TITLE
Undefined Behavior in `util::to_mut`

### ISSUE THREAD

**Issue by KrishnaSannasi** [xacrimon/dashmap#10]
You can never transmute a `&T` to a `&mut T` in *any* way. This is instant undefined behavior.

Currently there is no fast way to get a `(&K, &mut V)` from the standard hashmap, so your out of luck it seems, but there is a way to fix this! Instead of storing `HashMap<K, V>`, store `HashMap<K, UnsafeCell<V>>`. This way you can soundly get a `&mut V` from `get_key_value` (so long as you are also holding a write shard).

**Comment by KrishnaSannasi** [comment]
UB code: https://github.com/xacrimon/dashmap/blob/d3743b63ab589c6b2d9ee253719aeb4331000f02/src/util.rs#L36-L47

**Comment by xacrimon** [comment]
Thank you! I'll release a patch tomorrow.

**Comment by KrishnaSannasi** [comment]
I think a type like this will help,
```
pub SharedValue<T> {
    value: UnsafeCell<T>,
}

impl<T: Send> Send for SharedValue<T> {}
impl<T: Sync> Sync for SharedValue<T> {}

impl<T> SharedValue<T> {
    pub const fn new(value: T) -> Self {
        Self { value: UnsafeCell::new(value) }
    }
    
    pub fn get(&self) -> &T {
        unsafe { &*self.value.get() }
    }
    
    pub fn get_mut(&mut self) -> &mut T {
        unsafe { &mut *self.value.get() }
    }
    
    pub fn get_ptr(&self) -> *mut T {
        self.value.get()
    }
}
```

That way in the common case, you don't need to expand your usage of unsafe. This also (should) correctly implement `Send` and `Sync`

**Comment by xacrimon** [comment]
Awesome! Thanks again.

**Comment by KrishnaSannasi** [comment]
Do you mind if I send a PR?

**Comment by xacrimon** [comment]
That would be fantastic. If you do I'll have a patch out in a couple minutes after submission.
