### ISSUE TITLE
performance regression from 3.11.8 -> 3.11.9

### ISSUE THREAD

**Issue by L1AN0** [xacrimon/dashmap#100]
With 3.11.8:

read heavy
25165824 operations across 1 thread(s) in 1.67400416s; time/op = 65ns
25165824 operations across 7 thread(s) in 484.024319ms; time/op = 19ns
25165824 operations across 13 thread(s) in 375.786126ms; time/op = 14ns
25165824 operations across 19 thread(s) in 291.907019ms; time/op = 11ns
25165824 operations across 25 thread(s) in 428.060421ms; time/op = 17ns
25165824 operations across 31 thread(s) in 832.807807ms; time/op = 33ns
25165824 operations across 37 thread(s) in 1.154370526s; time/op = 45ns
25165824 operations across 43 thread(s) in 1.427097582s; time/op = 55ns
uniform
25165824 operations across 1 thread(s) in 2.761701491s; time/op = 109ns
25165824 operations across 7 thread(s) in 724.095403ms; time/op = 28ns
25165824 operations across 13 thread(s) in 543.72346ms; time/op = 21ns
25165824 operations across 19 thread(s) in 469.196739ms; time/op = 18ns
25165824 operations across 25 thread(s) in 752.106952ms; time/op = 29ns
25165824 operations across 31 thread(s) in 2.507433388s; time/op = 99ns
25165824 operations across 37 thread(s) in 3.598630391s; time/op = 142ns
25165824 operations across 43 thread(s) in 5.089173216s; time/op = 201ns

With 3.11.9:

read heavy
25165824 operations across 1 thread(s) in 1.61483007s; time/op = 63ns
25165824 operations across 7 thread(s) in 1.13014922s; time/op = 44ns
25165824 operations across 13 thread(s) in 1.142684288s; time/op = 44ns
25165824 operations across 19 thread(s) in 2.283061095s; time/op = 90ns
25165824 operations across 25 thread(s) in 2.908515261s; time/op = 115ns
25165824 operations across 31 thread(s) in 4.646918365s; time/op = 183ns
25165824 operations across 37 thread(s) in 6.844694052s; time/op = 271ns
25165824 operations across 43 thread(s) in 8.005175872s; time/op = 317ns
uniform
25165824 operations across 1 thread(s) in 2.868812834s; time/op = 113ns
25165824 operations across 7 thread(s) in 2.27564035s; time/op = 89ns
25165824 operations across 13 thread(s) in 8.997809418s; time/op = 356ns
25165824 operations across 19 thread(s) in 7.706663119s; time/op = 306ns
25165824 operations across 25 thread(s) in 6.872606461s; time/op = 272ns
25165824 operations across 31 thread(s) in 10.359676186s; time/op = 411ns
25165824 operations across 37 thread(s) in 14.388021271s; time/op = 571ns
25165824 operations across 43 thread(s) in 17.447989504s; time/op = 692ns

Code: https://github.com/L1AN0/bustle/blob/master/benches/dashmapv3.rs

Environment: AMD Ryzen 9 3900X 12-Core Processor

**Comment by xacrimon** [comment]
This is indeed quite wierd. I will take a look. Thanks

**Comment by xacrimon** [comment]
Out of curiosity, do you mind jacking up the shard count in lib.rs and seeing what happens?

**Comment by xacrimon** [comment]
fixed in 3.11.10
