### ISSUE TITLE
Producing *mut T from &T can be UB

### ISSUE THREAD

**Issue by Soveu** [xacrimon/dashmap#103]
[The line of code](https://github.com/xacrimon/dashmap/blob/acrimon/experimental/src/gc/queue.rs#L32)
Internal mutability without `UnsafeCell` is considered UB

**Comment by Soveu** [comment]
Possible fix
```rust
pub struct Queue<T> {
    head: AtomicUsize,
    next: AtomicPtr<Self>,
    nodes: [UnsafeCell<MaybeUninit<T>>; QUEUE_CAPACITY],
}
```

**Comment by xacrimon** [comment]
fixed, thanks
