### ISSUE TITLE
100% read scalability

### ISSUE THREAD

**Issue by gz** [xacrimon/dashmap#104]
I'm running a 100% read-only benchmark with dashmap on my 2 socket, 28 core skylake machine. I'm using the slightly modified `conc-map-bench` repo for it but this is essentially the change in the  workload configuration:

```rust
let m = Mix { read: 100, insert: 0, remove: 0, update: 0, upsert: 0 };
*Workload::new(n, m)
    .initial_capacity_log2(26)
    .prefill_fraction(1.0)
    .operations(5.0)
```

This is the result I'm seeing on the machine:
```log
335544320 operations across 1 thread(s) in 46.995141343s; time/op = 139ns
335544320 operations across 2 thread(s) in 31.326298818s; time/op = 92ns
335544320 operations across 3 thread(s) in 20.820673184s; time/op = 61ns
335544320 operations across 4 thread(s) in 17.552502098s; time/op = 51ns
335544320 operations across 5 thread(s) in 15.416198812s; time/op = 45ns
335544320 operations across 6 thread(s) in 12.566348539s; time/op = 36ns
335544320 operations across 7 thread(s) in 11.612739534s; time/op = 33ns
335544320 operations across 8 thread(s) in 10.693570668s; time/op = 31ns
```

I would expect 100% reads to scale linearly (if there is no false sharing and you use a scalable reader-writer lock in dashmap). However it seems this is not the case (but maybe I'm not interpreting the results correctly)?

One guess is that the performance could maybe improve if the locks (e.g., https://github.com/xacrimon/dashmap/blob/master/src/lock.rs#L11) would be on separate cache-lines (e.g., with the use of https://docs.rs/crossbeam/0.3.0/crossbeam/struct.CachePadded.html)?

**Comment by xacrimon** [comment]
Assuming you are using dashmap v3 in the conc-map-bench benchmark the issue that we are running into is contention on the lock state atomic since every read means an RMW on that lock. Scaling shards infinitely doesn't give great results either to due less and less shards ending up in cache and thus incurring cache misses and memory bandwidth limits.

**Comment by xacrimon** [comment]
This is just the nature of locking algorithms this coarse. v4 should help it significantly however.

**Comment by gz** [comment]
I'm using v3.11.1. Let me try v4 right now.

**Comment by gz** [comment]
Any chance there is an updated conc-map-bench repo that works with v4 out there? I can't seem to fetch the latest version: 

```
git pull
fatal: unable to access 'https://git.acrimon.dev/Acrimon/conc-map-bench.git/': Could not resolve host: git.acrimon.dev
```

Otherwise I can probably make my current checkout work with v4.

**Comment by xacrimon** [comment]
Ah, the repo is moved to my GitHub.

**Comment by gz** [comment]
Using `4.0.0-rc6`

```
335544320 operations across 1 thread(s) in 48.17555198s; time/op = 143ns
335544320 operations across 2 thread(s) in 26.589635699s; time/op = 78ns
335544320 operations across 3 thread(s) in 24.04951613s; time/op = 71ns
335544320 operations across 4 thread(s) in 13.275978167s; time/op = 38ns
335544320 operations across 5 thread(s) in 10.705068325s; time/op = 31ns
335544320 operations across 6 thread(s) in 8.483148188s; time/op = 24ns
335544320 operations across 7 thread(s) in 7.337641907s; time/op = 21ns
335544320 operations across 8 thread(s) in 6.621515431s; time/op = 18ns
```

I guess one idea would be to try and distribute the reader lock (e.g., something like this http://www.1024cores.net/home/lock-free-algorithms/reader-writer-problem/distributed-reader-writer-mutex or https://docs.rs/crossbeam/0.7.1/crossbeam/sync/struct.ShardedLock.html). Of course this has the trade-off that it can hurt write performance. Curious if you've considered this in the past already?

**Comment by xacrimon** [comment]
Well. V3 does this already. V4 takes no locks so that can be ruled out. Youre running into memory latency and bandwidth limits on that benchmark in terms of scaling. That said there are a lot more optimizations left to make on v4 that will help.

**Comment by xacrimon** [comment]
Further sharding each lock in v3 doesn't give a bit boost in reads and hurts writes a lot.
