### ISSUE TITLE
DashSet does not implement serde

### ISSUE THREAD

**Issue by Lexo-0** [xacrimon/dashmap#105]
DashMap implements serde, but why not for DashSet?

`error[E0277]: the trait bound `dashmap::DashSet<u8>: helloworld::_::_serde::Deserialize<'_>` is not satisfied`

**Comment by xacrimon** [comment]
Because I forgot it. I am currently very short on time. If you could submit a PR I could merge and release within a week or so.

**Comment by nico-abram** [comment]
Opened https://github.com/xacrimon/dashmap/pull/118 which should fix this
