### ISSUE TITLE
Please allow to remove the dependency on ahash

### ISSUE THREAD

**Issue by garbageslam** [xacrimon/dashmap#106]
This library looks very well thought out, and I was very interested to start playing with it,
but I was very disappointed to see this in the `Cargo.toml`:

```
[dependencies]
num_cpus = "1.13.0"
ahash = "0.3.8"
serde = { version = "1.0.114", optional = true, features = ["derive"] }
cfg-if = "0.1.10"
hashbrown = { version = "0.8.0", optional = true }
```

Here are the problems:

- `ahash` enables a very annoying `const-random` feature by default, which attempts to create randomness at built time in a build.rs and bake it into the binary. This is an enormous problem for many production build environments which require bit-for-bit reproducible builds, for logistical purposes and security purposes.

Because `dashmap` depends on `ahash` unconditionally, without giving me any option to reconfigure it or turn this off, it means that there's no way I can use this software in a serious project without patching `dashmap` to fix this.

You may ask, why does `ahash` turn on this feature by default if it's so bad?
This brings us to the second point.

- `ahash` is generally very poorly thought out and it is a bad idea to use it.

`ahash` is based on an idea to use a few rounds of the x86 AES instructions to create a decent hash, at least comparable to murmur hash.
However, `ahash` has no meaningful cryptographic properties, because it only does two AES rounds instead of the full 12. It is meaningless to claim that it is "DOS resistant but not cryptographically secure", which is exactly what the author has tried to argue repeatedly.
One reason that `ahash` is not used in the rust default hashmap, even though it is the default for `hashbrown`, is that security researchers raised concerns about `ahash`.

https://internals.rust-lang.org/t/a-new-default-hasher-for-hashmap/9747

DOS is an attack, and to defeat an attacker, you must satisfy a cryptographic security requirement. `ahash` documentation fundamentally rejects this idea -- they think they don't need a primitive like a PRF or a MAC. This is a mistake. `ahash` fundamentally is an attempt to roll-your-own cryptographic MAC function, based on totally ad-hoc arguments which are not widely accepted by researchers, nor subjected to peer review.

- `ahash` also treats the seed to the hash in an unsound manner -- that's the const-random thing.

It's not enough for the seed to be "randomly chosen at some point in time". The point of choosing it randomly at all is that it needs to be a secret. `ahash` is trying to cut corners. They think, well we want to be `no_std` and so we don't want to talk to the OS, or depend on `OSRng`, but then how do we get randomness at all? Well, why don't we bake some entropy into the binary at the build step? Horray, problem solved. Oh wait, what if the attacker gets the binary? Then they can extract the seed easily. Then the DOS resistance is broken and your webservice gets owned. Good luck to the poor engineers now working day and night trying to debug this.

This is not part of the threat model for any project that I've ever worked on. Modern security engineering embraces ideas like [Kerckhoff's principle](https://en.wikipedia.org/wiki/Kerckhoffs's_principle),
and rejects ideas like security through obscurity. It's assumed that it is okay to give out the binaries that run on your server -- to business partners, to contractors who may study them, or if your code is open source, to anyone.
Baking secret keys into the binary is a *terrible* idea, and this is exactly what `ahash` tries to do by default.

---

Please, don't use `ahash` thoughtlessly, just because it boasts good benchmark numbers. Use something that is better thought out, like siphasher, which is what rust stdlib uses. Siphasher is plenty fast for real applications -- the supposed performance benefits of `ahash` are only relevant to meaningless benchmarks. (The real-life benefits instead come from careful thinking about locks and contention that goes into dashmap :D )
Please give us some way to turn off the `const-random` at least, and ideally, the entire dependency on `ahash`, and swap in a sound hasher implementation.

**Comment by xacrimon** [comment]
Fixed in the incoming maintenance release.
