### ISSUE TITLE
Potential Issue in v4.0.0-rc6 on non-x86_64 targets.

### ISSUE THREAD

**Issue by trimoq** [xacrimon/dashmap#109]
In the Version `v4.0.0-rc6` currently on crates.io, there is an issue on non-x86_64 targets, using the fallback implementation.
Since I cannot find the code used on crates-io in this repo, I can't open a PR so let me explain what happens:
in `dashmap/src/spec/fallback.rs`, there occurs an index out of bounds problem:
`index out of bounds: the len is 8 but the index is 8', /home/XXXX/.cargo/registry/src/github.com-1285ae84e5963aae/dashmap-4.0.0-rc6/src/spec/fallback.rs:185:28`.
This seems to be caused by the increment in L201: `idx += 1;` without using a wraparound.
Changing this line to `idx = (idx + 1) % self.capacity();` solves the issue for me.

If you could point me to the sources on GH, I would be happy to prepare a PR.

**Comment by xacrimon** [comment]
V4 is currently in a state of limbo and seeing as it is an non semver version there is no support. I do not get paid to work on dashmap and thus I cannot spend a lot of time on it. V4 will come when I have time.
