### ISSUE TITLE
No std regression

### ISSUE THREAD

**Issue by Restioson** [xacrimon/dashmap#111]
Due to https://github.com/xacrimon/dashmap/commit/8a14a408a5355c925f178ece715fa176ef14b6b5 and https://github.com/xacrimon/dashmap/commit/fb0132a81708b0e91a1725a7171379002ddd5f9c, this no longer compiles on no std due to the added `num_cpus` dependency and ahash (which uses a positive `std` feature).

A possible fix would be to gate the num_cpus dependency behind `automatic_sharding` or whatever, and enable it by default. Then, to use this in no_std, default features would need to be turned off as well as the no_std feature turned on.

**Comment by xacrimon** [comment]
This is an option however I am forced to release v4 to fix outstanding issues and do maintenance and I currently lack the manpower for no-std support at release.
