### ISSUE TITLE
DashMap Concurrency problem

### ISSUE THREAD

**Issue by nishaq503** [xacrimon/dashmap#121]
I've been mulling over this for a few days now. Am I doing something wrong or is DashMap not thread-safe?

I have included code to reproduce the problem.

I have tried Arc::clone directly instead of the .clone() method but to no avail. I have also tried this with a DashSet by only inserting the len() of the DashSet in the helper function. I have tried several other variants too minor and numerous to list.

```rust
use std::sync::Arc;

use dashmap::Dashmap;
use rayon::prelude::*;

fn increments(num: usize, counter: Arc<DashMap<usize, ()>>) {
    for _ in 0..num {
        (*counter).insert((*counter).len(), ());
    }
}

fn test_dashmap() {
    let iterations = (0..100).collect::<Vec<usize>>();
    let counter: Arc<DashMap<usize, ()>> = Arc::new(DashMap::new());

    // a natural iter run
    iterations.iter()
        .map(|_| { increments(10000, counter.clone()) })
        .count();
    let single_count: usize = counter.len();

    // force a single-threaded run
    counter.clear();
    let pool = rayon::ThreadPoolBuilder::new().num_threads(1).build().unwrap();
    pool.install(|| {
        iterations.par_iter()
            .map(|_| { increments(10000, counter.clone()) })
            .count()
    });
    let single_pool_count: usize = counter.len();

    // a natural par-iter run
    counter.clear();
    iterations.par_iter()
        .map(|_| { increments(10000, counter.clone()) })
        .count();
    let threaded_count: usize = counter.len();

    assert_eq!(single_count, 1000000);
    assert_eq!(single_pool_count, 1000000);
    assert_eq!(threaded_count, 1000000);  // This fails
}
```

**Comment by xacrimon** [comment]
Version?

**Comment by nishaq503** [comment]
> Version?

dashmap version 3.11.10
rustc version 1.48.0

**Comment by nishaq503** [comment]
I have a suspicion that this is due to there not being a lock around the ```insert``` method. There may be a data race between getting the length and inserting it into the map. I have been trying to use a DashMap as a memo for a function being called many times in parallel.

**Comment by xacrimon** [comment]
Not sure. The insert method does acquire a shard lock.

**Comment by xacrimon** [comment]
Oh right. The length is not atomic and is not always in sync across all threads. You cannot rely on it for things like this.
