### ISSUE TITLE
Timeline to v4?

### ISSUE THREAD

**Issue by ckaran** [xacrimon/dashmap#122]
@xacrimon, thank you for creating this project, it looks like just what I need for my own project!

Is there a rough timeline for when version 4.0 will be released?  I'm really looking forwards to the fact that it can't deadlock, which will make my logic significantly easier (at the moment, I can't use DashMap because of potential deadlocking issues).

**Comment by xacrimon** [comment]
I do not have a timeline for v4 and it's fairly rough. This is due to most of my time being spent on my studies. I'm looking for people that would like to help but the people who have the expertise and time are few and far between.

**Comment by ckaran** [comment]
> This is due to most of my time being spent on my studies.

I fully understand (I'm finishing a PhD myself).

**Comment by xacrimon** [comment]
V4 with it's current featureset is now delayed indefinently until I have more time and due to the need for a new major maintenance release.
