### ISSUE TITLE
Documentation inconsistency

### ISSUE THREAD

**Issue by krojew** [xacrimon/dashmap#124]
The documentation for the map says:

> To accomplish these all methods take &self instead modifying methods taking &mut self. This allows you to put a DashMap in an Arc<T> and share it between threads while being able to modify it.

At the same time, any functions which access or modify the data are documented with:

> Locking behaviour: May deadlock if called when holding any sort of reference into the map.

One contradicts the other - having two Arcs holding references to the same map instance imply any data access can result in a deadlock. This means the map cannot actually be shared. While this is probably only a documentation issue, formally it means the map is not thread-safe. It would be great to explain how map can be safely used and how it shouldn't be used.

**Comment by xacrimon** [comment]
Noted in the upcoming maintenance release.
