### ISSUE TITLE
Request: Changelog

### ISSUE THREAD

**Issue by fosskers** [xacrimon/dashmap#129]
Considering that `4.0.0-rc6` to `4.0.1` has breaking API changes, could you provide a CHANGELOG or a migration guide?

**Comment by fosskers** [comment]
In my specific case, I'm wondering how to transition from `insert_and_get` to just `insert`, since the former no longer exists.

**Comment by fosskers** [comment]
This seems to do the trick:
```rust
        DOMAINS.insert(domain.clone(), data);
        DOMAINS.get(&domain).unwrap() // Safe because we just inserted it.
```

**Comment by fosskers** [comment]
See also https://github.com/kellpossible/cargo-i18n/pull/53

**Comment by xacrimon** [comment]
I probably won't do that. The reason is that rc versions are inherent in the name non semver compatible. In this case they were an experiment with a new design that had to be reverted due to the need for a maintenance update of v3.

**Comment by xacrimon** [comment]
RC versions aren't meant to be used in production. That's why they're not semver compatible and tools like cargo won't use rc versions unless explicitly told to.

**Comment by fosskers** [comment]
A downstream library I'm using in a project seemed to be using the `rc6`, but the PR I linked up there fixes it.
