### ISSUE TITLE
DashMap uses private serde module

### ISSUE THREAD

**Issue by thomcc** [xacrimon/dashmap#133]
If I attempt `cargo install tokei`, when building dashmap it fails with this error:

```
error[E0603]: module `export` is private
   --> /Users/thom/.cargo/registry/src/github.com-1ecc6299db9ec823/dashmap-3.11.10/src/serde.rs:5:12
    |
5   | use serde::export::PhantomData;
    |            ^^^^^^ private module
    |
note: the module `export` is defined here
   --> /Users/thom/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.119/src/lib.rs:275:5
    |
275 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0282]: type annotations needed
  --> /Users/thom/.cargo/registry/src/github.com-1ecc6299db9ec823/dashmap-3.11.10/src/serde.rs:58:38
   |
58 |         deserializer.deserialize_map(DashMapVisitor::<K, V>::new())
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `K`

error: aborting due to 2 previous errors
```

This is presumably the case for anything else using dashmap, at least with serde support.

The issue seems to be https://github.com/xacrimon/dashmap/blob/master/src/serde.rs#L5 which imports from a private module. You should instead use `core::marker::PhantomData` which is the same.

Ideally, you could fix this and also backport the fix to 3.x, e.g. cut a new patch release of 3.11.11 that contains just this minor fix, which will fix everything that is still depending on dashmap v3. (Obviously, you should also fix it for 4.x)

**Comment by thomcc** [comment]
This change happened in the most recent version of serde, e.g. https://github.com/serde-rs/serde/commit/dd1f4b483ee204d58465064f6e5bf5a457543b54

**Comment by ryzhyk** [comment]
Serde 1.0.119 broke semantic versioning by removing some std re-exports.  I ran into the same issue with my project.  Unfortunately, they wouldn't fix it: https://github.com/serde-rs/serde/issues/1946

**Comment by thomcc** [comment]
I think serde's stance is reasonable, although I'd assume stuff like this can happen due to cargo fix suggestions and/or r-a autoimport, so I'd probably be a bit more sympathetic.

Either way, it needs to be fixed downstream in crates like this one.

**Comment by nvzqz** [comment]
@xacrimon can you please also release 3.11.11 with this fix, so that downstream crates aren't required to update to 4.x (for 4.0.2)?
