### ISSUE TITLE
par_iter on a ReadOnlyView

### ISSUE THREAD

**Issue by njaard** [xacrimon/dashmap#136]
`ReadOnlyView::iter()` exists. There should be a `ReadOnlyView::par_iter()` too, so that it could be possible to do a `for_each` or `collect` on the items in parallel, with rayon.

**Comment by xacrimon** [comment]
Seems useful. Marked this as needs help, I'll accept patches for this feature if I get those before I get around to this myself.

**Comment by tomkarw** [comment]
Hey, I implemented this, simply copying the subset of rayon functionality for `DashMap` and relying on shards stored in `ReadOnlyVIew.map.shards`. 

Had to `pub(self)` or `pub(crate)` in 3 places in total, I hope that's okay, it's how standard library goes about things like that as well.
