### ISSUE TITLE
Feature request: Use parking_lot for RwLock

### ISSUE THREAD

**Issue by NathanHuisman** [xacrimon/dashmap#137]
[parking_lot](crates.io/crates/parking_lot) is a more efficient implementation of the rust synchronization primitives and more. [Tokio also uses it](https://docs.rs/tokio/1.0.2/tokio/index.html#internal-features). 

Its RwLock has multiple benefits compared to the std implementation including eventual fairness (prevents reader/writer starvation) and a performance improvement of up to 50x in some cases (although I'm not sure how much in this case)

For compatibility it could be implemented behind a feature flag that is off by default.

**Comment by xacrimon** [comment]
I'll consider it. Previously it wasn't used because dashmap needs the guards to be send and this was pre-send-guard feature era.

**Comment by JackThomson2** [comment]
I have a very rough prototype for running with parking_lot, noticed some speed increases and considerably more consistent between runs. It's live here https://github.com/jackthomson2/dashmap/tree/master/src

**Comment by estaban** [comment]
Is there any update on this issue? Could the PR be merged?

**Comment by xacrimon** [comment]
Fixed as of v5/master
