### ISSUE TITLE
Feature request: read-only "Entry" API

### ISSUE THREAD

**Issue by eggyal** [xacrimon/dashmap#143]
Suppose that one needs only an *immutable* reference to the value of a given key (but returning such a reference to a newly inserted value if none currently exists).

Of course, using the existing Entry API, one can do:

```rust
dash_map.entry(key).or_insert_with(Foo::bar).downgrade()
```

...but this _always_ requires that a write lock be obtained first, even if the entry already existed and a mere read lock would have been sufficient.

To avoid that, one can instead do:

```rust
match dash_map.get(&key) {
    Some(value) => value,

    // There's no race hazard here: even if another thread adds an entry for `key` to
    // the map between our dropping the read lock and acquiring the write lock, the
    // `Entry` API will simply return that entry -- and then we'll continue as if we'd
    // never known otherwise).
    None => dash_map.entry(key).or_insert_with(Foo::bar).downgrade(),
}
```

...but this is less efficient in the insertion case, as it involves hashing and looking up `key` twice.  :-(

It would be great if some variant of the Entry API could solve this little nit !

(PS: in my particular use case, these are the  _only_ accesses to the map that ever occur—and so even taking an upgradeable read lock for the initial lookup would be unsatisfactory, as it would effectively require every access to be exclusive: which is no better than the existing entry API).

**Comment by eggyal** [comment]
Actually, come to think of it, I guess the second lookup of `key` is unavoidable without an upgradeable lock... it should be possible to avoid hashing a second time, but perhaps that doesn't justify a dedicated API.

Happy to close this if there's nothing here?

**Comment by xacrimon** [comment]
👍
