### ISSUE TITLE
Could we get 3.x and 4.x fixes for serde internal breaking change usage?

### ISSUE THREAD

**Issue by doivosevic** [xacrimon/dashmap#146]
Could we please get releases containing https://github.com/xacrimon/dashmap/commit/cca7fd5320876ca9df2ba3428e9f87609b971361 fix? From what I understand, the change is from January and the last release is from December. Would also be nice if it could get backported to 3.x

**Comment by xacrimon** [comment]
4.0.2 fixes this if I am not incorrect. I will not update 3.x as it is buggy and it's use is heavily discouraged. Please talk to the maintainer of the dependent to update their dashmap version. Dashmap is mostly compatible from 3.x to 4.x and a migration should be a simple task.

**Comment by doivosevic** [comment]
My bad, I was looking at the "releases" tab in github and I saw 4.0.1 is the latest release but now I see on the badges that crates has 4.0.2. I believe that should be enough
