### ISSUE TITLE
Implement `Index`, `IndexMut` traits

### ISSUE THREAD

**Issue by jhpratt** [xacrimon/dashmap#147]
The [`Index`](https://doc.rust-lang.org/stable/std/ops/trait.Index.html) and [`IndexMut`](https://doc.rust-lang.org/stable/std/ops/trait.IndexMut.html) traits exist in `core`. Would it be possible to implement these traits for `DashMap`? They are implemented for `HashMap`.

**Comment by xacrimon** [comment]
These traits are sadly not implementable due to their definition. They are not compatible with a RAII wrapper around references into the map which is needed in order to synchronise between threads.

**Comment by jhpratt** [comment]
Ok, thanks for the response. Hopefully this issue will serve as a signpost for anyone looking in the future 🙂
