### ISSUE TITLE
Feature request: DashMap::try_insert()

### ISSUE THREAD

**Issue by nemarci** [xacrimon/dashmap#149]
A `try_insert` function would be useful to conditionally insert a new key-value pair if the key does not exist in the map. Currently I could implement it like this:

```rust
if !map.contains(&key) {
    map.insert(key, value);
}
```

Obviously, this has a huge drawback: it is not thread safe. I think that a function that does this in a thread safe way would be useful.

**Comment by Christopher22** [comment]
You may have a look at the [Entry API](https://docs.rs/dashmap/4.0.2/dashmap/mapref/entry/enum.Entry.html) which fulfils exactly your requirements.

**Comment by nemarci** [comment]
> You may have a look at the [Entry API](https://docs.rs/dashmap/4.0.2/dashmap/mapref/entry/enum.Entry.html) which fulfils exactly your requirements.

Thank you, looks like `or_insert` is the function that I'm looking for.
