### ISSUE TITLE
Feature request: !Send Ref

### ISSUE THREAD

**Issue by 0xdeafbeef** [xacrimon/dashmap#153]
Can we implement something like [this](https://docs.rs/lock_api/0.4.2/lock_api/struct.GuardNoSend.html) for [Ref](https://docs.rs/dashmap/4.0.2/dashmap/mapref/one/struct.Ref.html) under async or RefNotSend feature?

Use case: 
```rs
async fn fast_computation(data: &str) {
    tokio::time::sleep(Duration::from_secs(1)).await;
    drop(data);
}

async fn test(map: &DashMap<String, String>, data: &str) {
    let value = match map.get(data) {
        None => {
            tokio::time::sleep(Duration::from_secs(10)).await;  // some heavy computation
        }
        Some(a) => fast_computation(a.value()).await, // deadlocks here
    };
}
``` 

If `Ref` was not `Send`, then this won't compile.

**Comment by xacrimon** [comment]
Closed by #179 on v5. Release containing this will be put out later today.
