### ISSUE TITLE
Iterate over keys in `DashSet` and then consume it

### ISSUE THREAD

**Issue by YoshieraHuang** [xacrimon/dashmap#154]
Hi,
I am working on `DashSet` and I want to iterate over the keys and consume the set. I cannot find a convinient way to accomplish this.  Could you tell me how to do this?

**Comment by xacrimon** [comment]
DashSet is mainly meant for concurrent OLTP workloads. This isn't a common use-case and not something that has been implemented yet. I will keep this open to track any future implementation since we should support this.

**Comment by tomkarw** [comment]
Would it be as simple as implementing `IntoIterator` for `DashSet`? I can see `DashMap` already implements that, so exposing that in `DashSet` would be trivial.

I can do this if @xacrimon gives a green light.

**Comment by xacrimon** [comment]
@tomkarw green light, a welcome feature for sure, just not something I can personally prioritize time on atm, if you get some code together I will happily review this

**Comment by tomkarw** [comment]
Turns out `IntoIterator` is already implemented for `DashSet`: https://docs.rs/dashmap/latest/dashmap/struct.DashSet.html#method.into_iter. 

I guess this issue can be closed.
