### ISSUE TITLE
Feature request: ability to set the number of shards in DashMap

### ISSUE THREAD

**Issue by estaban** [xacrimon/dashmap#158]
It would be useful for `DashMap` consumers to be able to specify the number of internal shards. Some consumers might have low memory available and want to decrease the default number of shards. On the other hand, some consumers might want to decrease the probability of concurrent update within a single shard and increase this number.

**Comment by xacrimon** [comment]
Hi, this seems like a useful feature. Tagged/scheduled in the meantime until me or someone else gets around to this.

**Comment by leoleoasd** [comment]
Hi! I'm also interested in this feature, and I've made a PR (#185). I'm new to rust, so this PR may need thorough review, for example, I'm not sure why the default shard number is round up to `next_power_of_two`, and if we should limit the given shard amount the same way.

**Comment by xacrimon** [comment]
Closed by #185
