### ISSUE TITLE
Zipfian distribution in benchmarks

### ISSUE THREAD

**Issue by xacrimon** [xacrimon/dashmap#16]

**Comment by ben-manes** [comment]
If helpful, an example from a Java [benchmark](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/jmh/java/com/github/benmanes/caffeine/cache/GetPutBenchmark.java) showing how this can be structured, and the [results](https://github.com/ben-manes/caffeine/wiki/Benchmarks#server-class) on a 16-core box (as of roughly 2015).

**Comment by xacrimon** [comment]
Thank you!

**Comment by xacrimon** [comment]
This issue will receive process with dashmap V4 as benches will be revamped.
