### ISSUE TITLE
feature request: get_or_insert method

### ISSUE THREAD

**Issue by laralove143** [xacrimon/dashmap#169]
a utility method to do this, possibly more optimized, would be nice since i think it's used very often
```rs
let key = key();
let value = match dashmap.get(key) {
    Some(value) => value,
    None => {
        let default = default();
        dashmap.insert(key, default);
        default
    }
}
```
this way we could just do `let value = dashmap.get_or_insert(key(), default());`

**Comment by wangnengjie** [comment]
If `dashmap.get` returns `None`, then there is no lock guard for target shard and `dashmap.insert` may replace some value.
The `dashmap.entry` api can do this by
```rust
let dashmap = DashMap::<String, i32>::new();
dashmap.insert("a".to_string(), 1);
{
    let entry = dashmap.entry("a".to_string());
    match entry {
        Entry::Occupied(ref o) => println!("{}", o.get()),
        Entry::Vacant(_) => panic!("should not go here"),
    }
}
{
    let entry = dashmap.entry("b".to_string());
    match entry {
        Entry::Occupied(_) => panic!("should not go here"),
        Entry::Vacant(vacant) => {
            vacant.insert(2);
        }
    }
}
println!("{}", dashmap.get("b").unwrap().value());
```
Both `OccupiedEntry` and `VacantEntry` has a write guard to target shard so it's safe. (I don't know whether this api is stable?)
Problem is that `OccupiedEntry` will keep a write guard and for `get_or_insert` situation maybe you need a read guard? It seems that parking_lot provide some method to upgrade or downgrade the guard but I'm not so familiar with them.
I'm new to rust language. Please tell me if I have something wrong in the example code.

**Comment by laralove143** [comment]
do you  mean this is how it could be implemented? i don’t know how dashmap’s private code works but one of the contributors could probably come up with the best solution using methods that aren’t exposed publicly

**Comment by wangnengjie** [comment]
not exactly. I just show that your example code is not concurrent safe and if you had used it in your project to temporarily fill the lack of `get_or_insert`, you may need to have a look on your code. Just a kind reminder...
my example is only a compromise for the lack of api at this moment. It's sure that contributors can implemented it in a nice and effective way.

**Comment by xacrimon** [comment]
The entry API is stable and this is one of it's intended use cases. If this doesn't work for you and you have a proposition for a better API, please reopen. Closing as I don't want two API's that does the same thing.

**Comment by AshleySchaeffer** [comment]
For those stumbling across this in future. See a possible solution here:

https://github.com/xacrimon/dashmap/issues/292#issuecomment-1916621009

**Comment by geekbeast** [comment]
So I took a crack at implementing this here (#293) for reason mentioned in #78 #292. The work around in #292 works great, but ends up computing the usize hash and shard twice.
