### ISSUE TITLE
Dashmap 5.0.0 does not compile on wasm (stable)

### ISSUE THREAD

**Issue by dalcde** [xacrimon/dashmap#173]
`parking_lot` does not support compiling to wasm on stable.

**Comment by xacrimon** [comment]
Dashmap doesn't seek to run on wasm due to it being useless there since wasm doesn't do concurrency. It seeks to provide a concurrent drop-in replacement for the std hashmap for concurrent scenarios. Therefore wasm is not a target.

**Comment by dalcde** [comment]
My library is intended to work both natively and on wasm; on wasm
dashmap will just act as a simple hashmap. Can you reconsider?

**Comment by zicklag** [comment]
@dalcde it would probably be simple enough in your repo to do something like this:

```rust
#[cfg(not(target_arch = "wasm32"))]
pub use dashmap::DashMap as HashMap;

#[cfg(target_arch = "wasm32")]
use std::collections::HashMap;
#[cfg(target_arch = "wasm32")]
pub type HashMap = Rc::new(RefCell::new(HashMap));
```

**Comment by rektide** [comment]
WASI preview3 should support more asynchronous behaviors, first with cooperative multithreading (drafts landing now) and preemptive latter. Probably to soon to figure this out, but long term I'd love to see dashmap some-day updated to support wasm32-wasip3!
