### ISSUE TITLE
Not use the "sync_guard" feature of parking_lot

### ISSUE THREAD

**Issue by nullchinchilla** [xacrimon/dashmap#174]
`dashmap` uses the `sync_guard` feature of parking_lot. However, in my codebase, I use parking_lot throughout, and I intentionally want parking_lot guards to not be Sync, as defense against accidentally keeping them across `.await` points (which can easily lead to deadlocks).

But I cannot do so unless I downgrade dashmap to v4, because dashmap will turn on the `sync_guard` feature for me. This has caused several accidental deadlocks in my code already.

Can this be controlled at least by a feature flag? I don't want dashmap Refs to be Sync either.

**Comment by xacrimon** [comment]
This will be fixed in next v5. V5 is currently yanked due to a vulnerability and I'd recommend downgrading ASAP.

**Comment by xacrimon** [comment]
Fixed by #179
