### ISSUE TITLE
Iterate over keys

### ISSUE THREAD

**Issue by toasthorse** [xacrimon/dashmap#182]
Hello,

is there a way to iterate over all keys? I have a use case where I map port numbers to vectors of structs and would first want to check if the vector is empty and then remove it. The vectors are temporarily checked for timed-out entries, so they don't fill up indefinitely. So far I used the iter function to iterate over all values in the DashMap but this way I cannot get the corresponding key.

Thank you!

**Comment by xacrimon** [comment]
Hi, the iter() methods return a RefMultiple value which has a key() method in addition to derefing to a value reference. Please see the type docs.

**Comment by toasthorse** [comment]
My bad, I did not see that. Thanks for pointing it out!
