### ISSUE TITLE
Feature request: upsert

### ISSUE THREAD

**Issue by BrynCooke** [xacrimon/dashmap#188]
It'd be great if we could alter a `DashMap` but also supply an initial value in case the key has no value.

So instead of:
```rust
stats.insert("Goals", 4);
stats.alter("Goals", |_, v| v * 2);
```
The alternative would be:
```rust
stats.upsert("Goals", ||4, |_, v| v * 2);
```
It's particularly useful where the client doesn't necessarily get the option to populate the map with initial values in a separate phase of execution.

**Comment by BrynCooke** [comment]
Ahh, just saw: `.entry(...).or_insert_with(...)`
Sorry for the noise.

**Comment by xacrimon** [comment]
👍
