### ISSUE TITLE
Question - LRU possible?

### ISSUE THREAD

**Issue by liufuyang** [xacrimon/dashmap#189]
Hi there, I would like to ask what could be a way to have a LRU (least recently updated) feature attached onto dashmap so one can use it as a in-memory cache (sort of like Memcached).

Do anyone of know perhaps there are some packages that provide this utility? Or would it be easy/difficult to write one or even bring a feature like this in Dashmap? 

Would like to hear some of your opinions 👍 

Thank you :)

**Comment by xacrimon** [comment]
Hi @liufuyang, great question! Traditional ways to implement LRU caches will be quite hard to attach to dashmap internally in a way I'd be fine with releasing in this create but it's something that can be accomplished by combining dashmap with traditional LRU techniques like attaching a high performance concurrent linked list as done here https://github.com/Bajix/evlru.

**Comment by xacrimon** [comment]
Just came to think of it but the probabilistic scan LRU policy employed by Redis could probably also be combined quite well with dashmap.
