### ISSUE TITLE
Segfault on 32-bit platforms

### ISSUE THREAD

**Issue by Brekcel** [xacrimon/dashmap#19]
Currently on 32-bit platforms, DashMap causes a debug_assert failure/segfault in `DashMap::_yield_read_shard` and `DashMap::_yield_write_shard`. This is due to it being passed a garbage `i`, which it gets from `determine_map`. Currently, the hashing function used in `determine_map` is `fxhash::hash64`, which returns a u64. When that hash is later shifted, it's shifted based on the platform's pointer size. On 32bit platforms, this doesn't shift enough and causes the value returned from `determine_map` to be well out of bounds.

Changing the hash function from `hash64` to just `hash` (which returns a usize instead of a u64) seems to work for me so far.

For reference, I'm using this on a Raspberry Pi 2 Model B which uses the 32bit `armv7-unknown-linux-gnueabihf` target.

**Comment by xacrimon** [comment]
Thanks fort the report. Releasing a patch at 1500 GMT which fixes this.

**Comment by xacrimon** [comment]
Fixed on latest release.
