### ISSUE TITLE
Right-shift overflow

### ISSUE THREAD

**Issue by khionu** [xacrimon/dashmap#2]
I'm getting a panic from an overflow here: https://github.com/xacrimon/dashmap/blob/master/src/lib.rs#L147
In my code: https://github.com/rsimmonsjr/axiom/blob/master/src/executor.rs#L55

If this is intentional, should use the overflowing APIs: https://doc.rust-lang.org/std/primitive.usize.html

**Comment by xacrimon** [comment]
Overflow here is intentional. Fixing in 6 hours when I get access to a PC.

**Comment by xacrimon** [comment]
If you could submit an MR I can fix and publish right now.

**Comment by xacrimon** [comment]
This may be due to num_cpus returning 0. Going to investigate.

**Comment by xacrimon** [comment]
This bug turned out way more complicated than I thought. Though I've got a lead. Probably releasing a patch in about 4-5 hours.

**Comment by xacrimon** [comment]
Fixed in v2.1.1. Closing,
