### ISSUE TITLE
Userspace pure spinlocks (with no blocking path) perform very poorly in some situations

### ISSUE THREAD

**Issue by bsilver8192** [xacrimon/dashmap#206]
DashMap has some pure spinlocks (which never block in the kernel), which is a bad idea.

On my Linux system (Debian 5.15 kernel, standard configuration) with a test I wrote to demonstrate this, I see this behavior:
```console
brian[13661] rico ((here)) ~/Desktop/dashmap
$ cargo run --bin stress_test
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/stress_test`
Took: 2.914485973s. Min iteration: 631ns. 10% iteration: 721ns. 50% iteration: 808ns. 90% iteration: 1.335µs. 99% iteration: 2.524µs. Max iteration: 27.971394ms.
brian[13662] rico ((here)) ~/Desktop/dashmap
$ taskset 1 cargo run --bin stress_test
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/stress_test`
Took: 44.840032239s. Min iteration: 600ns. 10% iteration: 699ns. 50% iteration: 769ns. 90% iteration: 1.196µs. 99% iteration: 2.897µs. Max iteration: 387.522312ms.
```

It takes over 16x longer with both threads pinned to the same CPU, because when they contend a thread ends up spinning until the scheduler decides to switch to the other one. I suspect there are far worse cases, which tweaking the constants in this test could hit, although the "optimal" values will be machine-specific. Also, taking over 380ms to perform a single operation is a pretty severe tail latency.

I pushed my test to https://github.com/bsilver8192/dashmap/tree/stress_test-master, which is master as of today (270612e3f9edac5405c067da94b687230f471814, aka 5.3.3) + [my test](788e9260f52102dad120f24f3dafbe108235160b).

https://matklad.github.io/2020/01/02/spinlocks-considered-harmful.html goes into more detail about why this is not a good implementation. It links to https://matklad.github.io/2020/01/04/mutexes-are-faster-than-spinlocks.html which has some performance numbers indicating that this can be fixed with practically no cost in any case, and greatly increased speeds in some cases. It also links to https://probablydance.com/2019/12/30/measuring-mutexes-spinlocks-and-how-bad-the-linux-scheduler-really-is/ which shows some more examples of just how bad this can be.

**Comment by xacrimon** [comment]
I'm really well aware. I unfortunately had to push an emergency fix to the deadlock issues outlined previously that I had with parking_lot.

**Comment by xacrimon** [comment]
I am planning to switch to a better lock when possible, i.e I actually have some free time and I know about the disadvantages.

**Comment by bsilver8192** [comment]
Thanks! I understand it takes time. I misremembered the history here when I wrote the description, I had somehow convinced myself that the problem with parking_lot was the same, but it's really not. I'll post something here if I get time to try implementing an unfair rwlock with parking_lot_core, because that seems like the ideal solution.
