### ISSUE TITLE
No Try Remove API Similar To Try Get?

### ISSUE THREAD

**Issue by bonedaddy** [xacrimon/dashmap#207]
At the moment there does not appear to be an API that allows a failable remove operation without deadlocking the current thread. Is it possible to emulate this somehow? The only solution I can think of is a `try_get_mut` and them calling `std::mem::drop(value)` on the returned value

**Comment by xacrimon** [comment]
This can be accomplished using the entry API and it's remove operations on OccupiedEntry.
