### ISSUE TITLE
Inadvertent MSRV change to 1.59.0 in v5.3.0?

### ISSUE THREAD

**Issue by ahrens** [xacrimon/dashmap#211]
I noticed that with the integration of https://github.com/xacrimon/dashmap/pull/199, the MSRV is now 1.59.0 (due to use of [available_parallelism](https://doc.rust-lang.org/stable/std/thread/fn.available_parallelism.html)).  I also noticed that previous MSRV changes were part of major releases and were documented in the release notes (e.g. [5.0.0](https://github.com/xacrimon/dashmap/releases/tag/v5.0.0)).  But I did see that the MSRV in the README was [updated](https://github.com/xacrimon/dashmap/commit/0516c3cc65bf97a74e7e3a18b67c110b0f5ccd32) to 1.59.0.

So I was wondering if any of these changes were inadvertent, and if the project has any policy on what kinds of releases can contain MSRV changes.

FYI, personally, we tripped over this due to a misconfiguration of our build environment, and normally changing the MSRV in minor or even patch releases would be fine for us.  So this is more of a heads-up than a request to do things differently in the future.

**Comment by xacrimon** [comment]
Ah, yeah. This was unfortunately not too well considered, I wasn't aware how newly stabilized this API was. In the future, we intend only to do MSRV bumps in major releases and have a liberal policy to incrementing the major version.
