### ISSUE TITLE
add c interface 

### ISSUE THREAD

**Issue by calvin2021y** [xacrimon/dashmap#218]
please consider add simple c interface for dashmap.

```c
typedef uintptr_t HandleT;
typedef uint64_t KeyT;
typedef uint64_t ValT;

HandleT dashmap_new(void);
ValT dashmap_get(HandleT handle, KeyT key);
ValT dashmap_insert(HandleT handle, KeyT key, ValT val);
uintptr_t dashmap_length(HandleT handle);
void dashmap_destroy(HandleT handle);
```

**Comment by notgull** [comment]
Seconding. With `dashmap`'s impressive speeds, having an interface to another language would be a boon.

**Comment by zicklag** [comment]
For what it's worth, it's totally possible to create a separate crate to provide the C interface to DashMap, if somebody wanted to make one.

**Comment by xacrimon** [comment]
Hi, I don't consider this to be a priority and I don't have the bandwidth to maintain bindings, in addition, there are a lot of problems caused by generics we would somehow need to address.
