### ISSUE TITLE
Entry API: automatically clone/copy?

### ISSUE THREAD

**Issue by antifuchs** [xacrimon/dashmap#22]
I'm trying out the new entry API and it's really quite nice to use - it's a great ergonomics improvement! One thing that I notice though is that now, the only way I can tell of ensuring a key is present on the map is to get an owned key (via copy or clone), even if it should already be in the map (or if it might have gotten added in a parallel routine).

As far as I can tell, the most ergonomic way to adjust a key's value is something like this, which always clones (as opposed to a solution that probes via get first, then uses entries to initialize the entry without a race condition):

```rust
fn some_work(key: &K) {
    // key gets cloned for every access:
    let entry = self.entry(key.clone).or_default();
    return (*entry).do_the_work();
}
```

Now, when K should be Clone or Copy, I imagine something like this would be cool:

``` rust
fn some_work<K: Clone>(key: &K) {
    let entry = self.entry_cloning(key).or_default();
    return (*entry).do_the_work();
}
```

...where `.entry_cloning` returns a thing that's like `Entry`, except in `or_default` (and the other methods), it probes with a reference to the key first, then only if the key shouldn't be present, clones in order to insert it. (And same for `.entry_copying`...)

Does this make sense?

Alternatively, I'd like to understand how `.insert` behaves if the key being inserted is found - does it return the value that was present, does it overwrite the value? If there was a way for my code to ensure a value for the key is present (without overwriting) in the manual way, I'll take it too! (:

**Comment by xacrimon** [comment]
It makes total sense. Tbh I  just tried to mirror `std` here. How insert behaves depends on which insert. `or_insert` checks if an entry exists and if it does it returns a RefMut to it. insert on occupied entry returns the previous value and insert on VacantEntry returns a mutable ref to the inserted value.

**Comment by xacrimon** [comment]
It will force a clone though. Which is far from optimal. Which is why I wont be considering this.
