### ISSUE TITLE
Using the Default DashMap causes methods to panic

### ISSUE THREAD

**Issue by HiruNya** [xacrimon/dashmap#23]
If you obtain the DashMap using `DashMap::default`, any method used will cause a panic.
`DashMap::new` works fine.

(I'm using v3.0.7)

### Panic message
```thread 'main' panicked at 'attempt to shift right with overflow'```
### How to recreate
```rust
use dashmap::DashMap;
 
fn main() {                                           
    let map: DashMap<usize, ()> = DashMap::default();
    map.get(&1);
}
```
### Possible fix
Remove the derived Default implementation and replace it with a call to `new`. Or just remove it completely.

**Comment by xacrimon** [comment]
Thank you for the report. This issue has been fixed in master and a patch
is dropping 1500 GMT. I will close this when it's published.

**Comment by xacrimon** [comment]
Fixed on latest release.
