### ISSUE TITLE
A way to get `.key()`/`.value()`/`.pair()` with lifetime `'a` out of `RefMulti`?

### ISSUE THREAD

**Issue by GoldsteinE** [xacrimon/dashmap#230]
Currently the following code ([playground]) requires to allocate every sub-iterator:

```rust
use dashmap::DashMap;

struct Foo(Vec<u8>);
impl Foo {
    pub fn iter(&self) -> impl Iterator<Item = u8> + '_ {
        self.0.iter().copied()
    }
}

struct Bar(DashMap<String, Foo>);
impl Bar {
    pub fn iter_all(&self) -> impl Iterator<Item = u8> + '_ {
        self.0.iter().flat_map(|kv| kv.value().iter())
    }
}
```

Is there a reason why `RefMulti::value()` has signature `(&self) -> &V` and not `(&self) -> &'a V`?

[playground]: https://www.rustexplorer.com/b/p55fj4

**Comment by xacrimon** [comment]
Hi, this should be solvable with the `owning_ref` crate. That said, the reason for this is that an `RefMulti` cannot return a reference that could possibly life longer than oneself. The reason for this is that the various reference wrappers in dashmap keeps internal lock guards to parts of the `DashMap` which must be held open to prevent data races.
