### ISSUE TITLE
Question -How to fix it ::`(dyn WsSymbols + 'static)` cannot be sent between threads safely

### ISSUE THREAD

**Issue by dasauto2016** [xacrimon/dashmap#238]
```
pub type WsMapType = Arc<DashMap<String, Box<dyn WsSymbols>, RandomState>>;

lazy_static! {
    pub static ref WS_MAP:WsMapType = Arc::new(DashMap::new());
}

```

It occurs error: 
   | |_^ `(dyn WsSymbols + 'static)` cannot be sent between threads safely
   |
   = help: the trait `Send` is not implemented for `(dyn WsSymbols + 'static)`

**Comment by xacrimon** [comment]
Yep you have to do `(dyn WsSymbols + Send + Sync + 'static)`. I suggest getting familiar with dynamic trait objects using the Rust book.
