### ISSUE TITLE
Replace contents of dashmap with another

### ISSUE THREAD

**Issue by esemeniuc** [xacrimon/dashmap#247]
Is there a way to atomically replace the contents of a dashmap with another? Eg.

```rust
let a = DashMap::new();
a.insert("hi", 1);

let b = DashMap::new();
b.swap(a); // b now contains ("hi",1), and a is now empty.
```

**Comment by xacrimon** [comment]
Due to the design of the crate, this is not something that is doable. I suggest you look into the `arc-swap` crate.
