### ISSUE TITLE
Add an async API

### ISSUE THREAD

**Issue by Koxiaet** [xacrimon/dashmap#25]
Add an async API that won't block, so dashmap can be used in async contexts.

**Comment by xacrimon** [comment]
I did some research. Adding an async api won't help with anything. I even prototypes and tried it.

**Comment by Koxiaet** [comment]
Can you expand on this please? Do you recommend I use the blocking API for my async program or use a different library altogether?

**Comment by d4h0** [comment]
I'd be interested in this information as well, @xacrimon. Can DashMap V3 be used in an async context without a problem?

[I know](https://github.com/xacrimon/dashmap/issues/79), we can't keep a Ref guard bound across awaits, but are there any other known problems?

**Comment by xacrimon** [comment]
No other issues, safe to use in async.
