### ISSUE TITLE
Feature Flag Release

### ISSUE THREAD

**Issue by TTWNO** [xacrimon/dashmap#255]
Could you please publish a release to crates.io with the latest `hashbrown/inline-more` feature flag passthrough?

Thank you for all your hard (and free) work!

**Comment by bioinformatist** [comment]
@xacrimon Hi Joel, we also need this feature in our project for better performance. Thanks for your help.

**Comment by bioinformatist** [comment]
@TTWNO Currently you can use it in this way:

```toml
dashmap = { git = "https://github.com/xacrimon/dashmap.git", branch = "master", features = ["inline"] }
```

**Comment by xacrimon** [comment]
Yep. This is the current accepted solution as per the feature flags in the readme and `Cargo.toml`. Glad you like DashMap!
Thanks @bioinformatist for the informative and fast response.
