### ISSUE TITLE
HashSet abstraction

### ISSUE THREAD

**Issue by rsdy** [xacrimon/dashmap#34]
I've started playing around with DashMap, and I've already seen some impressive performance gains. One annoying thing that I have is that for a set, I've created the type alias:

    type DashSet<T> = DashMap<T, ()>

Which is fine, but the iterators behave weirdly, since the `Ref` dereferences by default to `.value()`, so now I always have to explicitly call `.key()` on the iterator item.

It would be nice to have a DashSet that fixes this syntactic quirk.

**Comment by xacrimon** [comment]
Sounds like a good idea! I'm marking this as help wanted since I am short on time and not sure when I can implement this.
