### ISSUE TITLE
spin is no longer actively maintained

### ISSUE THREAD

**Issue by jonasbb** [xacrimon/dashmap#37]
Crate:    spin
Title:    spin is no longer actively maintained
Date:     2019-11-21
URL:      https://rustsec.org/advisories/RUSTSEC-2019-0031

`spin` got added as a dependency in d20bc47d79c27b544965b36029dd1a84517aa655.
Unfortunately, the commit does not explain why the recommended crate is being replaced here.

**Comment by xacrimon** [comment]
This was due to me not realizing `spin` was abandoned. Patch inbound.

**Comment by xacrimon** [comment]
Fixed in latest release. Thank you!

**Comment by jonasbb** [comment]
Hi, thanks for fixing the issue so quickly 👍

**Comment by xacrimon** [comment]
No problem. I do my best to fix any UB or security issues like these within 12h.
