### ISSUE TITLE
Debug assertion failed

### ISSUE THREAD

**Issue by khionu** [xacrimon/dashmap#4]
Running my tests that create objects with Dashmaps inside them panics:
```
thread 'tests::test_simplest_struct_actor' panicked at 'assertion failed: i < self.shards.len()', C:\Users\Khionu\.cargo\registry\src\github.com-1ecc6299db9ec823\dashmap-2.1.1\src\lib.rs:440:9
```

**Comment by xacrimon** [comment]
Hello, would you fancy not using dashmap right now? I am quite busy and there seems to be bug fixing to be done.

**Comment by xacrimon** [comment]
I am preparing a new version that fixes this in a couple days time.

**Comment by khionu** [comment]
It's not a pressing priority for me. More of a compilation optimization.

**Comment by xacrimon** [comment]
V3 published, fixes all known bugs. Closing.
