### ISSUE TITLE
Avoid double hashing

### ISSUE THREAD

**Issue by tkaitchuck** [xacrimon/dashmap#40]
Right now the code hashes incoming keys twice. Once to select which inner map to use, and then internally by the map. 

This could be optimized by trading off a minor amount of memory. 
In the inner map instead of inserting the `K` directly, it could be a:
`HashMap<Key<K>, V>` where `Key` is defined as 
```
struct Key {
   hashCode: u64,
   userKey, K,
}
```
The inner maps could be set to use a Hasher which is designed to operate *exclusively* with this type, and which returns the hashCode as the hash every time. (Eq would be defined via the `userKey` only.)

Then the outer hasher could first select which map to send the data into (probably not using the lower bits of the hash to avoid collisions).

**Comment by xacrimon** [comment]
This would require changes in the public API. This issue will be solved in the next major version regardless.

**Comment by tkaitchuck** [comment]
This all looks like internal code. Why would it require an API change?

**Comment by xacrimon** [comment]
Reopening, forgot about the shard api being documented unstable. It should be possible. I'll give it a shot.
