### ISSUE TITLE
API similar to Ref::map

### ISSUE THREAD

**Issue by zimond** [xacrimon/dashmap#41]
Is there any chance that something similar to https://doc.rust-lang.org/std/cell/struct.Ref.html#method.map could be provided for `dashmap`'s `Ref` and `RefMut` types?

**Comment by xacrimon** [comment]
This is not possible. Refcell contains a single item and thus the type can be changes. It is merely a wrapper. DashMap contains multiple key value pairs and changing the type of one isn't possible.

**Comment by zimond** [comment]
Thanks for the explaination

**Comment by s97712** [comment]
I don't think it's impossible.
Modify the Ref signature to
```rs
pub struct Ref<'a, K, V, U, S = RandomState> {
    _guard: RwLockReadGuard<'a, HashMap<K, V, S>>,
    k: &'a K,
    v: &'a U,
}
```
Or create a new struct
```rs
pub struct RefMapped<'a, K, V, U, S = RandomState> {
    _guard: RwLockReadGuard<'a, HashMap<K, V, S>>,
    v: &'a U,
}
impl<'a, K: Eq + Hash, V, S: BuildHasher> Ref<'a, K, V, S> {
    #[inline]
    pub fn map<U, F>(orig: Ref<'a, K, V, S>, f: F) -> RefMapped<'a, K, V, U, S>
        where
            F: FnOnce(&V) -> &U,
    {
        let Ref{ _guard, k: _, v } = orig;
        RefMapped {
            _guard,
            v: f(v),
        }
    }
}
```

**Comment by s97712** [comment]
`RwLockReadGuard` and `RwLockReadGuard` may also be able to erase its type safely.
