### ISSUE TITLE
Lost updates with `Entry::or_*` methods

### ISSUE THREAD

**Issue by vitorenesduarte** [xacrimon/dashmap#47]
Hi. I was wondering if `Entry::or_*` methods (`or_default`, `or_insert` and `or_insert_with`) can result in lost updates. For example, if we have `let map: DashMap<String, AtomicU64> = DashMap::new();`, and then two threads execute the following code:
```rust
let value = map.entry(key).or_insert(AtomicU64::new(0));
value.fetch_add(1, Ordering::Relaxed);
```

Is it possible that the final value of the atomic is 1?  I was thinking that it might be possible if both threads can see that `key` does not exist and both `or_insert`, resulting in the lost of one of the `fetch_add`.

After writing this, I think I have a more clear question: is it possible that `or_*` methods insert in an `Entry::Occupied`?

Thanks.

**Comment by xacrimon** [comment]
Since the guard created by the first method is a unique one this should not be possible.

**Comment by vitorenesduarte** [comment]
Not sure if the following makes sense but: is there a place in the code where this can be checked, and if so, can we `panic!` in that case?

**Comment by xacrimon** [comment]
Well, all this should be guarded by the internal shard locks. If you somehow manage to obtain concurrect access to that we have a bug in a dependency.

**Comment by xacrimon** [comment]
The first step of both of these methods is indeed to acquire a lock on the containing shard. And that lock isn't dropped until the reference guard into the map is.

**Comment by vitorenesduarte** [comment]
That makes sense. I just took a look at the code and if I understand correctly, threads will acquire a write lock [here](https://github.com/xacrimon/dashmap/blob/master/src/lib.rs#L656), meaning that *only one* of the threads can see the `Entry::Vacant`. Thanks for clarifying.

**Comment by vitorenesduarte** [comment]
Hi @xacrimon. Will this API (or something equivalent) be supported in v4? Thanks.

**Comment by xacrimon** [comment]
Entry* cannot fundamentally be supported at this level due to the absence of locks. Instead, a retryable compare and swap method to swap the value of a bucket will be exposed. In order to enable an Entry* like Api you would need to implement an MVCC layer on top.

**Comment by vitorenesduarte** [comment]
Will it be possible to do a "insert-if-not-exists" with this retryable CAS?

**Comment by xacrimon** [comment]
Yup

**Comment by vitorenesduarte** [comment]
Great, thanks!

**Comment by vitorenesduarte** [comment]
Hi again @xacrimon. Under enough concurrency, I'm seeing calls to `entry` hanging forever. I've pushed here a self-contained example: https://github.com/vitorenesduarte/dashmap-entry
It should be enough to run `make`, which will run the example several times, and it should hang after some runs. Once that happens, a file called `LOG` should show that threads are blocked calling `entry`.

This example uses `parking_lot`, since that's what I was using when I noticed this problem, but it shouldn't be needed. I'll try to simplify it.

**Comment by vitorenesduarte** [comment]
I've pushed a simplified branch (https://github.com/vitorenesduarte/dashmap-entry/tree/atomics) where atomics are used instead of `parking_lot::Mutex`.

**Comment by xacrimon** [comment]
Just before I dig in, are you following the locking policies in the docs?

**Comment by vitorenesduarte** [comment]
Just read the one in `entry` ("May deadlock if called when holding any sort of reference into the map.") and that may exactly be the problem. Thanks. Will v4 improve this kind of situations?

**Comment by xacrimon** [comment]
It will.
