### ISSUE TITLE
Please don't use `qadapt-spin`

### ISSUE THREAD

**Issue by koushiro** [xacrimon/dashmap#49]
Please don't use `qadapt-spin`, which is just an early fork version of  [spin-rs](https://github.com/mvdnes/spin-rs) that apply `rustfmt`, nothing else changed.

If you don't use spin-rs just because it is [no longer actively maintained](https://rustsec.org/advisories/RUSTSEC-2019-0031), I think you can consider using `lock_api` (At least, I think `spin-rs` is better than `qadapt-spin`).

**Comment by xacrimon** [comment]
Noted. Thank you. I'll look into this soon.

**Comment by xacrimon** [comment]
Fixed
