### ISSUE TITLE
compatibility with serde

### ISSUE THREAD

**Issue by pythoneer** [xacrimon/dashmap#5]
Hi, id like to make a feature request. I am currently replacing a `RwLock<HashMap>` and it works really good so far and the fact that i do not need to acquire a lock manually is really nice. The biggest inconvenience i have within my current code base is that i frequently use serde to (de)serialize the `std::collections::HashMap`. I think having this as an optional feature would add value to your implementation.

**Comment by xacrimon** [comment]
Hello. I am going to put up a notice but for now please use V1. Some hard to fix bugs have been found in V2. Also I do not have time for that right now sadly. The earliest I can add this is in January. Thank you for your understanding.

**Comment by pythoneer** [comment]
Thank you for bringing this to my attention. The Codebase i am working right now is not considered for immediate production use. Anyway is the V1 roughly API compatible? I would guess because it resembles `std::collectcions::HashMap` quite well.

For the on topic question, i implemented it myself for the time being by wrapping DashMap (because of the orphan rules) it was pretty straight forward. I guess i could take a shot by creating a PR if your schedule does not allow for it. If i would do that, what do you think is better – implementing it for V1 or V2 ... idk how heavy you expect things to change in V2 due to your bug fixing if at all.

**Comment by xacrimon** [comment]
I'd hold off on implementing it now honestly. V1 is fairly compatible with
V2.

**Comment by pythoneer** [comment]
I can live with it in its current form. I think we can revisit this when things have settled and V2 is fixed.

**Comment by pythoneer** [comment]
btw, i've added a workaround [here](https://github.com/xacrimon/dashmap/issues/5#issuecomment-567883129) for others to see, that you may haven't noticed because you're using email and edits of posts are not reflected in email conversations if i remember correctly.

**Comment by xacrimon** [comment]
Implemented in v3 with the `serde` feature.
