### ISSUE TITLE
v3.4.2 has a bug

### ISSUE THREAD

**Issue by kdy1** [xacrimon/dashmap#52]
I have no idea about what is happening but pinning dashmap version to 3.4.0 fixed the tests.

See: https://github.com/swc-project/swc/pull/633#issuecomment-583235251

**Comment by xacrimon** [comment]
Interesting, I'll take a look.

**Comment by xacrimon** [comment]
Found the issue, thank you. I'll be releasing a patch update in 10 hours. Affected versions are yanked.

**Comment by xacrimon** [comment]
Fixed in the latest patch update.

**Comment by kdy1** [comment]
Great. Thanks!
