### ISSUE TITLE
Ability to take all key value pairs out of a DashMap

### ISSUE THREAD

**Issue by dsherret** [xacrimon/dashmap#53]
I'm currently receiving a DashMap from some code external to mine and do not need the concurrency. To eliminate the performance overhead and added complexity the concurrent api brings, I would like to be able to take out all the data and store it in a `HashMap` (I am doing many many lookups into the map).

Previously when they used a CHashMap I was able to do the following:

```rust
let map: HashMap<Key, Value> = c_hash_map.into_iter().collect();
```

It would be nice to have a similar API or perhaps a single `.take()` method.

Would this change be possible? Right now I am cloning all the pairs out of the DashMap, which is not ideal.

Thanks!

**Comment by xacrimon** [comment]
Thanks for the suggestion, I will implement IntoIter and make a release on Friday.

**Comment by xacrimon** [comment]
Due to time constraints I will have to delay a little.

**Comment by dsherret** [comment]
@xacrimon that's cool! No rush at all 🙂

**Comment by xacrimon** [comment]
Added in latest release.

**Comment by dsherret** [comment]
@xacrimon awesome. Thanks so much!
