### ISSUE TITLE
remove_with_condition

### ISSUE THREAD

**Issue by Future2100** [xacrimon/dashmap#56]
I want to remove an entry when the entry's value matches the condition.

**Comment by Future2100** [comment]
Awesome, I am glad to hear that.

**Comment by Future2100** [comment]
Btw, I had a pull request for that, please check.

**Comment by xacrimon** [comment]
Taking a look at that today.

**Comment by hlb8122** [comment]
I was about to open an issue concerning this because I have the exact same requirement.

**Comment by xacrimon** [comment]
Patch rolling in today.

**Comment by xacrimon** [comment]
Added in latest release.
