### ISSUE TITLE
#[derive(Default)] for DashMap mandates that keys/values be Default

### ISSUE THREAD

**Issue by antifuchs** [xacrimon/dashmap#6]
I'm upgrading DashMap in my project (from 1.2.0 to 2.1.0), and noticed that a new requirement got added that is a bit difficult for me to implement: the `Default` impl for `DashMap` now [requires](https://docs.rs/dashmap/2.1.1/dashmap/struct.DashMap.html#impl-Default) that `<K: Default, V: Default>` also.

I think this might be unintentional - I don't see a reason why [`::new()`](https://docs.rs/dashmap/2.1.1/dashmap/struct.DashMap.html#method.new) shouldn't require Default-ness on Keys and the `Default` impl would.

**Comment by xacrimon** [comment]
Ah yes, I should really put up a notice and yank the 2.x versions. I found a whole slew of sneaky bugs in 2.x and I will be releasing a rewrite as soon as I have time. Therefore I advise against using 2.x versions for now.

**Comment by antifuchs** [comment]
Good to know, thanks!

**Comment by antifuchs** [comment]
Ah, I'm reopening this as the latest release (3.0.7) still has the somewhat spurious `Default` requirements for `K` and `V`; I'm happy to open a PR for a manual/non-derive Default impl if you prefer (:

**Comment by xacrimon** [comment]
I just merged a PR that changed this due to an erroneous default implementation. Patch fixing this will be released 1500 GMT today.

**Comment by antifuchs** [comment]
Now that's fast!! Thanks (:

**Comment by xacrimon** [comment]
Fixed on latest release.
