### ISSUE TITLE
Add or_try_insert_with method in Entry

### ISSUE THREAD

**Issue by ufoscout** [xacrimon/dashmap#61]
Currently, the `Entry` struct has a `or_insert_with` method that accepts a callback to provide a default value; anyway, there is no way to pass a fallible closure.
So, I wonder if it is possible to add the following method to the `Entry` struct:

```rust  
#[inline]
pub fn or_try_insert_with<E>(self, value: impl FnOnce() -> Result<V, E>) -> Result<RefMut<'a, K, V, S>, E> {
    match self {
        Entry::Occupied(entry) => Ok(entry.into_ref()),
        Entry::Vacant(entry) => Ok(entry.insert(value()?)),
    }
}
```

This would allow this use case where dashmap is used as a local cache for value loaded, for example, from a remote storage:
```rust
let my_value = my_dashmap
     .entry(&"hello")
     .or_try_insert_with(fetch_from_db("hello"))
     .unwrap();
```

**Comment by xacrimon** [comment]
Fixed in dashmap v3.6.0. Thank you.
