### ISSUE TITLE
Turn dashmap into read-only mode?

### ISSUE THREAD

**Issue by w1th0utnam3** [xacrimon/dashmap#65]
I have a common pattern in a library where I first collect data into a hashmap (only writing) and then process it (only reading). 

During the reading stage, the `RwLock` and `Ref` wrappers prevent me from storing _raw references to the values_ in the `DashMap` in an auxiliary structure, even though this would be perfectly ok, because I don't want to perform any more writes.

For me, it would therefore be nice to have a functionality like `RwLock`'s [`.into_inner()`](https://doc.rust-lang.org/std/sync/struct.RwLock.html#method.into_inner) which moves data out of the lock. For `DashMap` it would basically turn it into a map without concurrent write support. Do you think that this would be a useful addition to the library? I could have a look at this when I have some free time.

**Comment by xacrimon** [comment]
This definently sounds like a worthy addition. I don't have time for implementing right now but I have the design. It would boil down to making a wrapper type for dashmap that ignores wlocks unsafely and only has read methods which can then return raw references.

**Comment by xacrimon** [comment]
If you decide to implement it I'll review and merge it.

**Comment by w1th0utnam3** [comment]
Yes, a wrapper sounds sensible. So, to implement this, we need the following:

1. Add a method `pub fn get(&self) -> &T` to your `RwLock` implementation.
2. Add a wrapper type `ReadOnlyView<Map>` that supports all read operations of `DashMap`:
    - `capacity() -> usize`
    - `get(&Key) -> Option<&Value>` or `get(&Key) -> Option<(&Key, &Value)>` however, I don't think the later makes much sense, and the former would be more consistent with the `HashMap` interface.
    - `is_empty() -> bool`
    - `iter() -> impl Iterator<Item = (&Key, &Value)>`
    - `len() -> usize`

    These would be essentially the same implementations as for the `DashMap`, but would use the new `RwLock::get()` method.
3. To convert between the map and the wrapper:
    - add a consuming `DashMap::into_read_only(self) -> ReadOnlyView<Self>`
    - add a consuming `ReadOnlyView<Map>::into_inner(self) -> Map`

Maybe we could even add `keys() -> impl Iterator<Item = &Key>` and `values() -> impl Iterator<Item = &Value>` to be more consistent with the standard `HashMap`? I'm not sure yet, how the internals of DashMap would affect iteration. Didn't look at it in detail.

**Comment by xacrimon** [comment]
Yep that sounds good. Key and value iterators are very simple. Just take the regular iterator and discard one of the two.
