### ISSUE TITLE
Plans for V4

### ISSUE THREAD

**Issue by DavidBM** [xacrimon/dashmap#67]
Hi! 

First of all, congratulations for this fantastic piece of work. I'm using it in an actor system and it is the main corner stone for it.

I was reading that you want to build a V4, what the changes you have in mind? Would you accept help? If yes, I would like to see if there is anything that I can help. 

Btw, if this is not your preferred channel for this kind of questions, let me know. 

Best! :smile:

**Comment by xacrimon** [comment]
Hi! I do want to build a v4 and have started in the experimental branch. I've switched up the design completely. v4 will be fully lockfree and is a lot faster. I'm a good bit of the way there but significant work remains. There is stuff to do but extensive knowledge of low level processor architecture and lockfree datastructures and algorithms is required so the entry bar is quite high

For now I think I'll be best of working by myself for a little while. I'm expecting to release v4 in May this year and after that I'll be working on my high school graduation paper on it. 

Glad you've found dashmap useful.

**Comment by DavidBM** [comment]
Thanks for the response! I will follow your implementation, it will help me to learn about this topics.
And if I can help in any way, let me know!

**Comment by DavidBM** [comment]
One question @xacrimon. Would the V4 has the entry method? 
I'm assuming that not as I see you removed all the locks. Am I right?
