### ISSUE TITLE
Open issues for known bugs

### ISSUE THREAD

**Issue by skeet70** [xacrimon/dashmap#7]
I'm using V1 and am intending to use it in production. You've mentioned on a few issues that you found several bugs with V2, and your attention seems to have shifted to https://github.com/ixy-db. Would you mind creating issues here for the known bugs to enable someone else to picking them up?

**Comment by xacrimon** [comment]
Really the entire code base needs to be rechecked and some parts rewritten. There are too many subtle bugs for me to list accurately. The main thing that seems to be broken is how references are implemented and the standard iterator api. I have been working on a patch I'm hoping to get out today or tomorrow.

**Comment by xacrimon** [comment]
So no need for anybody to pick it up. I will close this when the patch is released.

**Comment by xacrimon** [comment]
v3 published and fixes all known bugs.
