### ISSUE TITLE
Implement clone_from on DashMap

### ISSUE THREAD

**Issue by TyPR124** [xacrimon/dashmap#70]
The `Clone` trait has an optional `clone_from(&mut self, source: &Self)` method. It would be good to manually implement this method so that users can avoid some extra allocations/deallocations when they need to `clone_from`.

**Comment by xacrimon** [comment]
Closing this due to the very small amount of savings in comparison to the rest of the codebase where you would reasonably be using this and due to the fact v4 is due to release soon.
