### ISSUE TITLE
DashSet does not implement Debug

### ISSUE THREAD

**Issue by mjhostet** [xacrimon/dashmap#75]
After upgrading to DashMap 3.10.0 I tried to replace `DashMap<X, ()>` with `DashSet`.

It almost worked, except `DashMap` implements `Debug` and `DashSet` does not, so I could no longer `#[derive(Debug)]` on my struct containing the `DashSet` field.

Also, `std::collections::HashSet` implements `Debug`, so `DashSet` should too.

**Comment by xacrimon** [comment]
Thanks for the report. I've scheduled a patch and a release in 17 hours that fixes this.

**Comment by xacrimon** [comment]
Will have to delay slightly due to time constraints.

**Comment by xacrimon** [comment]
Fixed in 3.11.0.
