### ISSUE TITLE
DashMap shard number conflicts with HashBrown tag

### ISSUE THREAD

**Issue by mjhostet** [xacrimon/dashmap#76]
std::collections::HashMap's HashBrown algorithm uses the high 7 bits of the hash as its tag for SIMD comparisons: https://github.com/rust-lang/hashbrown/blob/f7bb664f41b1c74d2c5dcbab55727227b9e8d13a/src/raw/mod.rs#L129

DashMap also uses those same high bits of the hash to pick its shard: https://github.com/xacrimon/dashmap/blob/57b72aec4dae96ed8ee10ac90f8ac6c5ecb439eb/src/lib.rs#L279

This means that, since there are 4 shards per core, if you have 32 or more cores, every SIMD tag in the same shard will be equal, ruining the effectiveness (but not correctness) of HashBrown's parallel tag match algorithm. Even with fewer cores, the effectiveness will be substantially reduced.

The easiest fix is probably just to do:

```
// Leave the high 7 bits for the HashBrown SIMD tag.
let shard = (hash << 7) >> shift;
```

Alternatively, multiply is slower but does a good job of mixing low bits into high bits, so something like:

```
// Multiply by golden ratio (as a usize) to mix into the high bits.
let golden_ratio = (0x9e3779b97f4a7c15u64 >> (64 - util::ptr_size_bits())) as usize;
let shard = hash.wrapping_mul(golden_ratio) >> shift;
```

This is a few cycles slower than the `<< 7`, but has the advantage of not magically "knowing about" the underlying HashMap's 7 bit tags. It will also choose a good shard even for a poor hash function that leaves the high bits zero, like certain uses of [nohash-hasher](https://docs.rs/crate/nohash-hasher/0.2.0), although of course those would suffer from poor SIMD tags anyway.

**Comment by xacrimon** [comment]
Fixed in 3.11.0.
