### ISSUE TITLE
DashMap should not use spinlocks with std

### ISSUE THREAD

**Issue by mjhostet** [xacrimon/dashmap#77]
DashMap uses its own spinlock library, and its RwLock never suspends the thread (e.g. as with `std::thread::park`).

Userspace spinlocks can yield disastrously bad (orders of magnitude worse) performance when the machine is running more threads than cores, as explained [here](https://matklad.github.io/2020/01/02/spinlocks-considered-harmful.html). I have seen this class of bug cause an outage of a major production system and it makes me nervous about using DashMap.

I don't have any suggestions for what to do in the no_std case, but for the std case it's important to use use either std or parking_lot locks so control is eventually yielded back to the OS. They are quite fast (they will spin for a while before giving up, use exponential backoff, use hardware lock elision if available, etc.)

**Comment by xacrimon** [comment]
Thanks for the report. I am well aware of this issue and it's something I've tried to resolve. Unfortunately luck guards from std and parking_lot are not transferable between threads which makes dashmap really unwieldy to use. I made this tradeoff right now and it is something that will be fixed in V4 which is in development.

**Comment by mjhostet** [comment]
Thanks for the explanation! What's the thread handoff used for? I didn't notice it.

**Comment by xacrimon** [comment]
I want element guards to be Send in order to make working with DashMap in an async environment convenient. This is due to the restriction that all locals that live across an await point have to be Send.

**Comment by xacrimon** [comment]
This was an issue reported back in V2 and spinlocks were used to address it in V3. Thankfully I did stumble upon an end-all-be-all solution for V4. I expect to release that in June.
