### ISSUE TITLE
Suggestions on how to make dashmap.retain() work with multiple threads

### ISSUE THREAD

**Issue by tasleson** [xacrimon/dashmap#82]
I'm using dashmap for a problem and it's working great except for one thing.  During the processing I'm using a number of threads to insert data into a single dashmap with rayon.  Once the threads are done I want to cull the dashmap, eg. `hash.retain(|_, v| v.len() > 1);`  For large data sets the map can have > 22M entries and after the `retain` we end up with ~1M entries.  For the duration of the retain which takes about ~5 seconds on my system we are single threaded.  I've tried a number of different approaches, but I've not been able to get this to work with threads.  I keep thinking that I would need exposure to the `self.shards.iter` to use a `par_iter`, any suggestions on how I could speed up the retain?

I do the `retain` for a couple of reasons, but the main one is to lower memory consumption.

**Comment by xacrimon** [comment]
Can you try doing `map.shards().iter().par_bridge().for_each(|shard| shard.write().retain(fn));` ?

**Comment by tasleson** [comment]
> Can you try doing `map.shards().iter().par_bridge().for_each(|shard| shard.write().retain(fn));` ?

OK, I wasn't aware I could utilize private things, but I saw the `raw-api` feature and it does appear to work with:

```rust
        map
        .shards()
        .iter()
        .par_bridge()
        .for_each(|s| s.write().retain(|_, v| v.get().len() > 1));
```
note the added `v.get()`

Thanks!

**Comment by xacrimon** [comment]
You're welcome!
