### ISSUE TITLE
v3.11.5 contains a breaking change on ARM

### ISSUE THREAD

**Issue by Lokathor** [xacrimon/dashmap#88]
The [ahash crate has a bug in 0.4](https://github.com/tkaitchuck/aHash/issues/37) which makes the crate not build outside of x86 / x86_64. `dashmap-3.11.4` used `ahash-0.3` and then `dashmap-3.11.5` uses `ahash-0.4`.

Please add additional CI for both ARM and wasm32 builds to avoid this unfortunate mix up before.

Also, probably yank `dashmap-3.11.5` and wait until `ahash` can issue a fix before releasing `dashmap-3.11.6`

**Comment by xacrimon** [comment]
Yanked, thank you. Will add more CI.
