### ISSUE TITLE
Allow user to supply the hasher

### ISSUE THREAD

**Issue by Shnatsel** [xacrimon/dashmap#9]
`std::HashMap` defaults to SipHash for DoS resilience but allows passing a custom hasher via [with_hasher](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.with_hasher) and [with_capacity_and_hasher](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.with_capacity_and_hasher) methods. It would be very nice to allow the same in DashMap.

I understand it currently defaults to FxHash, so this is actually strictly required for DoS resilience.

**Comment by ethanhs** [comment]
I can take this! I started working on it because I may want to use it.

**Comment by xacrimon** [comment]
That would be fantastic! Sounds good.

**Comment by xacrimon** [comment]
Assigned you.

**Comment by xacrimon** [comment]
Fixed on latest release.
