### ISSUE TITLE
`into_key` missing on `OccupiedEntry`

### ISSUE THREAD

**Issue by Ten0** [xacrimon/dashmap#94]
`into_key()` is missing on [`OccupiedEntry`](https://docs.rs/dashmap/3.11.7/dashmap/mapref/entry/struct.OccupiedEntry.html)

That is useful for scenarios where you want to:
 - Check whether the key is present
 - If not, insert using VacantEntry
 - If it is present, do nothing but reuse the key (`occupied_entry.into_key()`)

That method exists on VacantEntry.

**Comment by xacrimon** [comment]
Added.
