### ISSUE TITLE
v4.0.0-rc6: DashMap::insert sometimes end up with duplicate keys

### ISSUE THREAD

**Issue by teozkr** [xacrimon/dashmap#95]
See https://github.com/clux/kube-rs/issues/286. https://github.com/clux/kube-rs/pull/287 contains a regression test and instructions for how to repro (basically, insert and remove items ~randomly for a little while and things will break, even on a single thread).

**Comment by xacrimon** [comment]
Thanks for trying the beta versions and finding this out. This will be addressed before the full release. I will be keeping this open.

**Comment by xacrimon** [comment]
Closing this for now as it is not a release version.
