### ISSUE TITLE
V4: Returning reference to ElementGuard value

### ISSUE THREAD

**Issue by d4h0** [xacrimon/dashmap#96]
Hi,

I have a DashMap that contains a struct that contains a HashMap, and I have 3 operations that I need to do on this HashMap.

One operation looks like this:

```rust
        self.sessions // the DashMap
            .get(&self.session_id)
            .unwrap()
            .value()
            .event_handlers // the HashMap
            // the actual operation:
            .insert(
                // the other operations are `remove` and `contains_key`
                TypeId::of::<E>(),
                E::wrap_event_handler(callback)
            );
```

Because the code to get the HashMap is always the same, I tried to create a helper function that returns the value of an EntryGuard:

```rust
    fn session(&mut self) -> &DevToolsProtocolSession {
        self.sessions.get(&self.session_id).unwrap().value()
    }
```

But I get the following error:

> cannot return value referencing temporary value returns a value referencing data owned by the current function

It seems the ElementGuard value is tied to the ElementGuard, which I don't understand because the value is a reference to my `DevToolsProtocolSession`. Is this ElementGuard newly created, and the owner of `DevToolsProtocolSession`?.

At the moment, I just repeat the code to get the HashMap, but I'm wondering if there is a way to archive what I tried above.

**Comment by xacrimon** [comment]
Concurrent memory management and synchronization is achieved by wrapping returned references in Ref and RefMut structs from the library. You have to return those reference wrappers instead.

**Comment by d4h0** [comment]
Wow, that was fast! :)

I just realized that my code doesn't even work because `ElementGuard` values can't be mutated. 

It seems the only option is `update`,  but this would require that I create a completely new value instead of updating the existing value (because the type of `do_update` is `FnMut(&K, &V) -> V`).

Is that correct? Am I doing something wrong? Is there an easy way to update my HashMap in the DashMap without recreating the complete DashMap value?

Sorry if this all is obvious, I'm pretty new to Rust.

**Comment by xacrimon** [comment]
Ah you're on v4, I'd recommend using v3 for the time being. The v4 releases are betas and have known bugs. v3 entries can be mutated if you use get_mut.

**Comment by d4h0** [comment]
Oh, okay. I thought the "rc6" in the version means V4 is almost ready.

Will V4 also have "get_mut" when it is released?

**Comment by xacrimon** [comment]
It won't, this is due to a larger architectural difference. V4 removes all locks so in place mutation isn't possible unless the user mutexes the value manually.

**Comment by d4h0** [comment]
Thanks for your help, @xacrimon. After switching to V3 everything works as expected.

Do you have a rough estimate when V4 will be ready?

**Comment by xacrimon** [comment]
I don't. I have too much going on in my life right now and there is a lot of work to be done. And there simply aren't many people that can help out with this stuff. Requires a lot of prerequisite experience and knowledge.

**Comment by d4h0** [comment]
Okay, thanks again.
