### ISSUE TITLE
Does `iter` guarantee that all elements are going to be found?

### ISSUE THREAD

**Issue by bikeshedder** [xacrimon/dashmap#97]
As far as I understand hash tables they will perform rehashing when the capacity is increased. The current documentation of dashmap states this for the `iter` method:

> ```rust
> pub fn iter(&self) -> Iter<K, V>
> ```
> 
> Create an iterator over all entries in the map. This does not take a snapshot of the map and thus changes during the lifetime of the iterator may or may not become visible in the iterator.

That leaves one question open: Is it guaranteed that all elements of the map which were not changed while iterating to be reached? I'm using the map in a concurrent application and I don't care about insertions and removals not showing up during iteration. I just want to be sure that inserting `A` or removing `B` don't cause `C` to be missing when iterating over the map.

I might be looking at the wrong data type for my use case though. I'm using `dashmap` to store connections keyed by a connection id and need to iterate over them to send out broadcasts to all connected clients. That's why I'm asking if the iterator is guaranteed to reach all elements even in the case of a rehashing happening.

Does this also work in `dashmap` v4 which is supposedly completely lock free?

**Comment by xacrimon** [comment]
Your assumption is indeed correct. All elements in the map will be iterated over. It works the same in V4 but I cannot recommend using that because it is not done and has bugs still.

**Comment by bikeshedder** [comment]
Wow. Thanks for the fast reply!

Is it fine to have "slow iterators" or or should I make sure to create a copy of the elements and release the iterator as fast as possible?

Maybe that's something that could be added to the API docs. I had a bad feeling using `DashMap` that way even though the docs state that it behaves like a drop in replacement for `RwLock<HashMap>`. :grimacing:

**Comment by xacrimon** [comment]
In mostly cases it works as a drop in replacement but it isn't optimal. Getting optimal performance out of V3 is a bit tricky, that's the main reason for me creating V4. Slow iterators are often fine but keep in mind they read lock the shard they are iterating over. Which may potentially block writes to that shard. V3 is essentially a very optimized list of rwlocked hashmaps. The iterator keeps a read lock on the shard it is currently on. That's also why a locking policy is specified on each method in the v3 documentation that says what you can and cannot do without deadlocking. Deadlocks being another primary reason for starting work on v4.

**Comment by xacrimon** [comment]
Getting optimal performance out of v3 involves keeping locks for the shortest time possible, eagerly dropping Ref and RefMut variables when possible to release the shard lock.

**Comment by bikeshedder** [comment]
I'm actually using `DashMap<usize, Arc<T>>` for ownership of a list of T and `DashMap<usize, Weak<T>>` for storing subsets of the first map. I'll make sure to never do do blocking calls or `.wait` for a future while holding on to an iterator. If I really need to perform any blocking calls I'll clone all the values returned by `iter` and use the copy instead.

In case you're curious; my usecase for dashmap is the following:

- `DashMap<usize, Arc<Connection>>` is a collection of all connected clients to a server
- `DashMap<usize, Weak<Connection>>` are subsets of those clients
- `DashMap<Topic, Dashmap<usize, Weak<Connection>>>` is used to implement a pubsub like service

Thanks for the great crate!

**Comment by bikeshedder** [comment]
Just to be sure I created a little stresstest application and for the fun of it also gave DashMap 4 a try:

### DashMap 3 (debug build)

```
real	0m30,848s
user	8m3,245s
sys	0m0,260s
```

### DashMap 3 (release build)

```
real	0m6,222s
user	1m37,700s
sys	0m0,044s
```

### DashMap 4 (debug build)

```
real	0m3,660s
user	0m49,637s
sys	0m0,991s
```

### DashMap 4 (release build)

```
real	0m1,059s
user	0m9,223s
sys	0m1,361s
```

## Comparison

I find the performance characteristics quite interesting:

- DashMap 4 is ~8.5x faster in the debug build and ~6x faster in release build
- DashMap 3 is ~5x faster in release build than in debug build
- DashMap 4 is ~3.5x faster in release build than in debug build
- DashMap 4 in debug build is still faster than DashMap 3 release build

## Code

Here is the code I used:

```rust
use std::sync::Arc;
use std::thread;
use std::time::Duration;
use dashmap::DashMap;

const MAP_SIZE: usize = 10_000;
const MAP_RO: usize = 10;
const THREAD_ITERATIONS: usize = 100;
const THREAD_COUNT: usize = 100;

fn worker(map: Arc<DashMap<usize, ()>>, step_size: usize) {
    let mut insert = (step_size / 2) % 2 == 0;
    for _ in 0..THREAD_ITERATIONS {
        for i in (MAP_RO..MAP_SIZE).step_by(2) {
            if insert {
                map.insert(i, ());
            } else {
                map.remove(&i);
            }
            insert = !insert;
        }
    }
}


fn main() {
    let map = DashMap::<usize, ()>::new();
    for i in 0..MAP_SIZE {
        map.insert(i, ());
    }
    let map = Arc::new(map);
    let mut join_handles = Vec::<thread::JoinHandle<()>>::new();
    for i in 0..THREAD_COUNT {
        let map = map.clone();
        join_handles.push(thread::spawn(move || worker(map, i)));
    }
    // sleep for 1 millisecond and let the threads do their job
    thread::sleep(Duration::from_millis(1));
    let mut found = 0;
    for it in map.iter() {
        if *it.key() < MAP_RO {
            found += 1;
        }
        thread::sleep(Duration::from_micros(10));
    }
    assert_eq!(found, MAP_RO);
    for join_handle in join_handles {
        join_handle.join().unwrap();
    }
}
```

I won't be using DashMap 4 until you consider it stable of course. I just found that to be quite impressive.

**Comment by bikeshedder** [comment]
I have one more technical question regarding this issue. How does DashMap guarantee that adding elements while iterating over it can not change the order of elements and thus miss some of them? The only solution I can think of is locking the entire map and make capacity changes and rehashing impossible while an iterator exists.

How does that work in DashMap 4 if it is lock-free? I guess that special case still requires lock or is there some amazing algorithm that I just don't know about, yet?

**Comment by xacrimon** [comment]
In V3 a part of the map is locked and it inserted. This means the insertion happens either before or after the iterator traverses that region.

For V4, well insertions can happen in the middle but I don't understand how that would cause it to miss some of them. At a high level the V4 iterator is looping through the bucket array and checks each index.

**Comment by bikeshedder** [comment]
Sorry for the noise. I need to look at the actual implementation and figure that out on myself.

Thanks a lot! :+1:

**Comment by xacrimon** [comment]
No problem. If you have more questions, ask me here, on email or on discord at acrimon#2954.
